### ISSUE TITLE
이슈 테스트

### ISSUE THREAD

**Issue by srngch** [42JalS/url-shortener#4]
아이디어
- 1번
- 2번
- [ ] #5
- [ ] 4번
- [ ]  분할1
- [ ] 분할2

구현 기능
기능에 대한 설명

**Comment by srngch** [comment]
기능 분할 아이디어 
- [ ] 분할1
- [ ] 분할2

**Comment by EeeUnS** [comment]
- [1] chaejkim: 기존 서비스 중에서 한글 이모지 도메인⭐️
    - 글타래 모으기
- [1] yunselee : shorts url 넣으면 원본 url 띄우기
- [2] yunselee : 커스텀 url @CJ K
- [3] yunselee : api 제공.
- [4] sarchoi: 주소바에서 바로 만들 수 있는 단축 URL(api)
- [4] yunselee : chrome 확장프로그램, 슬랙봇 확장.
- [4] chaejkim: 메타데이터에서 제목 가져와서 url 주소 만들기(model)
- [5] sarchoi: [https://linktr.ee/](https://linktr.ee/) + URL Shortener 합친 서비스
- [6] minjekan: 통계, 필터링?
